package com.jinglebroda.domain.model.searchRecipeModel.test

enum class HealthLabels( val value:String) {
    AlcoholCocktail("Alcohol-Cocktail"),
    AlcoholFree("Alcohol-Free"),
    CeleryFree("Celery-Free"),
    CrustceanFree("Crustcean-Free"),
    DairyFree("Dairy-Free"),
    DASH("DASH"),
    EggFree("Egg-Free"),
    FishFree("Fish-Free"),
    FODMAPFree("FODMAP-Free"),
    GlutenFree("Gluten-Free"),
    ImmunoSupportive("Immuno-Supportive"),
    KetoFriendly("Keto-Friendly"),
    KidneyFriendly("Kidney-Friendly"),
    Kosher("Kosher"),
    LowPotassium("Low Potassium"),
    LowSugar("Low Sugar"),
    LupineFree("Lupine-Free"),
    Mediterranean("Mediterranean"),
    MolluskFree("Mollusk-Free"),
    MustardFree("Mustard-Free"),
    NoOilAdded("No oil added"),
    Paleo("Paleo"),
    PeanutFree("Peanut-Free"),
    Pescatarian("Pescatarian"),
    PorkFree("Pork-Free"),
    RedMeatFree("Red-Meat-Free"),
    SesameFree("Sesame-Free"),
    ShellfishFree("Shellfish-Free"),
    SoyFree("Soy-Free"),
    SugarConscious("Sugar-Conscious"),
    SulfiteFree("Sulfite-Free"),
    TreeNutFree("Tree-Nut-Free"),
    Vegan("Vegan"),
    Vegetarian("Vegetarian"),
    WheatFree("Wheat-Free"),
    //Список ниже я не добил, завтра попробуй крч отправить json запрос в нейронку.
}